name: nblensing
channels:
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - namaster
  - pip
  - pip:
    - pyFFTW
    - tqdm
    - scipy
    - matplotlib
    - numpy
    - seaborn
    - astropy

